name: update

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Создать папки
        run: mkdir -p deploy/subscriptions
        
      - name: Создать тестовый файл
        run: echo "test $(date)" > deploy/test.txt
        
      - name: Коммит
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add deploy/
          git commit -m "test $(date)" || exit 0
          git push
